# Generated by Django 3.1.4 on 2020-12-05 21:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unnamed1',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(0)], verbose_name='名称1'),
        ),
        migrations.AddField(
            model_name='user',
            name='unnamed2',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(1000)], verbose_name='名称2'),
        ),
        migrations.AddField(
            model_name='user',
            name='unnamed3',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(1000)], verbose_name='名称3'),
        ),
        migrations.AddField(
            model_name='user',
            name='unnamed4',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(regex='[0-9a-zA-Z]{1:10}')], verbose_name='名称4'),
        ),
    ]
